version: '3.8'
services:
  gospel-backend:
    build: .
    container_name: gospel-backend
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - USE_SUPABASE=true
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    networks:
      - gospel-network

networks:
  gospel-network:
    driver: bridge


