version: '3.8'

services:
  gospel-bot:
    image: probedrik/gospel-bot:latest
    container_name: gospel-bot
    restart: unless-stopped
    
    # Переменные окружения из файла .env
    env_file:
      - .env
    
    # Дополнительные переменные окружения
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - TZ=UTC
    
    # Монтирование томов для данных и логов
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./config:/app/config:ro  # Только для чтения
    
    # Проверка здоровья
    healthcheck:
      test: ["CMD", "python", "-c", "import asyncio; print('Bot is healthy')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # Ограничения ресурсов
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    
    # Сеть
    networks:
      - gospel-bot-network
    
    # Логирование
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Опциональный сервис для мониторинга (можно раскомментировать)
  # watchtower:
  #   image: containrrr/watchtower
  #   container_name: gospel-bot-watchtower
  #   restart: unless-stopped
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   environment:
  #     - WATCHTOWER_POLL_INTERVAL=3600
  #     - WATCHTOWER_CLEANUP=true
  #     - WATCHTOWER_INCLUDE_STOPPED=true
  #   command: gospel-bot

networks:
  gospel-bot-network:
    driver: bridge

# Именованные тома для постоянного хранения данных
volumes:
  gospel-bot-data:
    driver: local
  gospel-bot-logs:
    driver: local