name: gospel_bot_flutter
description: Flutter app for Gospel Bot with local Bible assets and Supabase sync
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.5.3
  http: ^1.2.1
  provider: ^6.1.2
  collection: ^1.18.0
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/rst.json
    - assets/rbo.json

